---
name: Build and publish the container image

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Get tag
        id: repository
        run: echo  "::set-output name=tag::$(git describe --tags HEAD)"

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Build and push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.repository.outputs.tag }}
            docker.io/${{ github.repository }}:${{ steps.repository.outputs.tag }}
