name: Release binaries on github

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      -
        name: test build binaries
        if: github.ref_name == 'master'
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --snapshot --clean
      -
        name: release binaries
        if: github.ref_name != 'master'
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
